try{document.execCommand('BackgroundImageCache',false,true);}catch(e){}
var isIE=!-[1,];var isGecko=(navigator.userAgent.indexOf("Gecko")>-1)&&(navigator.userAgent.indexOf("KHTML")==-1);function $$(o){if(document.getElementById&&document.getElementById(o)){return document.getElementById(o);}else if(document.all&&document.all(o)){return document.all(o);}else if(document.layers&&document.layers[o]){return document.layers[o];}else{return false;}}
function setCls(o,c,f){if(!o)return;var oc=o.className=o.className.replace(new RegExp('( ?|^)'+c+'\\b'),'');if(!f)o.className=oc.length>0?(oc+' '+c):c}
String.prototype.trim=function(){return this.replace(/(^\s*)|(\s*$)/g,"");}
if(!Array.prototype.indexOf)Array.prototype.indexOf=function(item,i){i||(i=0);var l=this.length;if(i<0)i=l+i;for(;i<l;i++)if(this[i]===item)return i;return-1}
function isEmail(s){var p=/^([a-zA-Z0-9_-])+@([a-zA-Z0-9_-])+(\.[a-zA-Z0-9_-])+/;return p.test(s)}
function isUrl(s){var p=new RegExp("((^http)|(^https)):\/\/(\\w)+\.(\\w)+");return p.test(s)}
function onEvent(A,B,C){B=B.replace(/^on/,'').toLowerCase();if(A.attachEvent){A[B+C]=function(){C.call(A,window.event)};A.attachEvent('on'+B,A[B+C])}else A.addEventListener(B,C,false);return A}
function unEvent(A,B,C){B=B.replace(/^on/,'').toLowerCase();if(A.attachEvent){A.detachEvent('on'+B,A[B+C]);A[B+C]=null}else A.removeEventListener(B,C,false);return A}
function show(){this.style.display='block'}
function hide(){this.style.display='none'}
function setVisibile(A,B){if(typeof A=='string')A=$$(A);if(A)A.style.display=B?'block':'none'}
function bytes(s){if(typeof(s)!="string"){s=s.value}var l=0;for(var i=0;i<s.length;i++){if(s.charCodeAt(i)>127){l++}l++}return l}
function preloadImage(){var args=preloadImage.arguments;if(!document.preloadImageArray)document.preloadImageArray=[];for(var i=0,len=args.length;i<args;i++){document.preloadImageArray.push(new Image());document.preloadImageArray[document.preloadImageArray.length].src=args[i]}}
function Extend(A,B){for(var C in B){A[C]=B[C]}return A}
function CurrentStyle(A){return A.currentStyle||document.defaultView.getComputedStyle(A,null)}
function Bind(A,B){var C=Array.prototype.slice.call(arguments).slice(2);return function(){return B.apply(A,C.concat(Array.prototype.slice.call(arguments)))}}
function forEach(A,B,C){if(A.forEach){A.forEach(B,C)}else{for(var i=0,len=A.length;i<len;i++)B.call(C,A[i],i,A)}}
var Tween={Quart:{easeOut:function(t,b,c,d){return-c*((t=t/d-1)*t*t*t-1)+b}},Back:{easeOut:function(t,b,c,d,s){if(s==undefined)s=1.70158;return c*((t=t/d-1)*t*((s+1)*t+s)+1)+b}},Bounce:{easeOut:function(t,b,c,d){if((t/=d)<(1/2.75)){return c*(7.5625*t*t)+b}else if(t<(2/2.75)){return c*(7.5625*(t-=(1.5/2.75))*t+.75)+b}else if(t<(2.5/2.75)){return c*(7.5625*(t-=(2.25/2.75))*t+.9375)+b}else{return c*(7.5625*(t-=(2.625/2.75))*t+.984375)+b}}}}
function setHomepage(){if(document.all){document.body.style.behavior='url(#default#homepage)';document.body.setHomePage('http://'+document.domain)}else if(window.sidebar){if(window.netscape){try{netscape.security.PrivilegeManager.enablePrivilege("UniversalXPConnect")}catch(e){alert("该操作被浏览器拒绝，如果想启用该功能，请在地址栏内输入 about:config,然后将项 signed.applets.codebase_principal_support 值该为true")}}var prefs=Components.classes['@mozilla.org/preferences-service;1'].getService(Components.interfaces.nsIPrefBranch);prefs.setCharPref('browser.startup.homepage','http://'+document.domain)}}
function addFavorite(){if(document.all){window.external.addFavorite(window.location.href,document.title)}else if(window.sidebar){window.sidebar.addPanel(document.title,window.location.href,'')}}
function Switch(o){var c=o.parentNode.children[1];if(c.style.display=='none'){o.className='category_bown';c.style.display='block';}}
function inittab(o,t,n,e,c,callback){var tab=$$(o);if(!tab||tab.isinit)return;tab.isinit=true;var ul=$$(o+'-body');if(!ul)return;var tabs=tab.getElementsByTagName(t||'li');if(!tabs||tabs.length==0)return;tab=tabs[0].parentNode;tab.uls=[];if(n&&n.indexOf('.')>0){var t=n.split('.');var els=ul.getElementsByTagName(t[0]);for(var i=0,len=els.length;i<len;i++){if(els[i].className.split(' ').indexOf(t[1])>=0)tab.uls.push(els[i]);}}else{n=n||'ul';for(var i=0,len=ul.childNodes.length;i<len;i++){if(ul.childNodes[i].tagName&&ul.childNodes[i].tagName.toLowerCase()==n)tab.uls.push(ul.childNodes[i]);}}
if(!tab.uls)return;var cls=c||'current';e=e?e:'onmouseover';tab.lis=tabs;for(var i=0;i<tabs.length;i++){tabs[i].i=i;if(i>0&&tab.uls[i])tab.uls[i].style.display='none';tabs[i][e]=function(){var u=this.parentNode;var idx=u.act?u.act:0;setCls(u.lis[idx],cls,true);if(u.uls[idx])u.uls[idx].style.display='none';u.act=this.i;setCls(this,cls);if(u.uls[this.i])u.uls[this.i].style.display='';if(callback&&typeof callback=='function'){callback.call(null,i,this,u.uls[this.i])}}}}
var BLOCK_AUTO_ID=0;function excms_block(url){++BLOCK_AUTO_ID;document.write('<div id="block_'+ BLOCK_AUTO_ID+'"></div>');ajax.update('block_'+ BLOCK_AUTO_ID,'get','/apps/include.php',{'file':url});}
function showSoCate(A){if(!A.M){M=A.parentNode.getElementsByTagName('span')[1],A.M=M,M.A=A;A.onmouseover=function(){this.M.onmouseover()}
A.onmouseout=function(){this.M.onmouseout()}
M.onmouseover=function(){this.style.display='block'}
M.onmouseout=function(){this.style.display='none'}
M.onclick=function(e){e=e||window.event;var el=e.target||e.srcElement;if(el.tagName.toLowerCase()=='a')this.onmouseout();}
A.onmouseover();}}
function setSoCate(O,V){$$('so_category').value=typeof V!='undefined'?V:'';$$('so_cate_txt').innerHTML=O.innerHTML;$$('so_input_q').focus();var p=O.parentNode;setCls(p.current||p.getElementsByTagName('a')[0],'current',1)
p.current=O;setCls(O,'current');}
function setSoKeywords(A,E){var V=A.value.trim();if(!A.defaultValue)A.defaultValue=V;if(V!=A.defaultValue&&V!='')return;A.value=E=='focus'?'':A.defaultValue;setCls(A,'so-key-focus',E!='focus');}
function soSubmit(F){var A=$$('so_input_q');var B=A.value.trim();if(B==''||(A.defaultValue&&B==A.defaultValue)){A.focus();return false;}
return true;}
function initLinkSo(f){f=$$(f);if(!f)return;var d=f.getElementsByTagName('div');var c,s;for(var i=0;i<d.length;i++){if(d[i].className=='cate_list'){c=d[i];}else if(d[i].className=='cate_selected'){s=d[i];}}
if(!c)return;var a=c.getElementsByTagName('a');var k=f['keywords'];if(k){k.defautValue='请输入关键字';k.value=k.defautValue;k.onfocus=function(){if(this.value==this.defautValue)this.value='';setCls(this,'focus')}
k.onblur=function(){if(this.value=='')this.value=this.defautValue;if(this.value==this.defautValue)setCls(this,'focus',true)}}
if(s&&a.length){var cat=f['category'];s.onclick=function(){c.style.display='block'}
c.onmouseover=function(){this.style.display='block'}
c.onmouseout=function(){this.style.display='none'}
var t='';for(var i=0;i<a.length;i++){if(a[i].attributes['selected']&&a[i].attributes['selected']=='1'){t=this.innerHTML;}
if(cat){a[i].onclick=function(){s.innerHTML=this.innerHTML;cat.value=this.attributes['value'].value;c.style.display='none';}}}
s.innerHTML=t==''?a[0].innerHTML:t;}}
function checkLinkSo(o){if(o.keywords.value==''||o.keywords.value==o.keywords.defautValue){o.keywords.focus();return false;}
return true;}
var tiggerSoTimer,triggerSoEl;function triggerSoLeft(A){var B=A.className=='colse';setCls(A,'colse',B);triggerSoEl=A.parentNode.parentNode.parentNode;triggerSoLeftMove(B?0:132);}
function triggerSoLeftMove(A){var C=Math.abs(parseInt(CurrentStyle(triggerSoEl)['marginLeft']));if(isNaN(C))C=0;if(A==C)return;if(tiggerSoTimer)clearTimeout(tiggerSoTimer);var D=C<A?1:-1,E=D*(A- C),F=Math.ceil(E/2);C+=D*F;C=-C;triggerSoEl.style.cssText+=';margin-left:'+ C+'px';tiggerSoTimer=setTimeout(function(){triggerSoLeftMove(A)},10);}
function initSlider(A){var A=$$(A);var L=A.getElementsByTagName('li');var i,len=L.length;if(len==0)return;var C=document.createElement('div');C.className='slider-tab';A.appendChild(C);setVisibile(L[0],true);var UL=document.createElement('UL');C.appendChild(UL);var H='';var a,li,sd,t;for(i=0;i<len;i++){if(i==0)L[i].style.display='block';a=L[i].getElementsByTagName('a')[0];img=L[i].getElementsByTagName('img')[0];sd=document.createElement('em');sd.className='txt-shadow';img.parentNode.insertBefore(sd,img);li=document.createElement('li');li.view=L[i];t=a.innerText||a.textContent;li.innerHTML='<a href="'+ a.href+'" target="_blank" title="'+ t+'"><img src="'+ img.src+'" /></a>';UL.appendChild(li);}
UL.current=UL.getElementsByTagName('li')[0];setCls(UL.current,'current')
UL.onmousemove=function(e){e=e||window.event;var el=e.target||e.srcElement;var n=el.tagName.toLowerCase();if(n=='a'||n=='img'){el=n=='a'?el.parentNode:el.parentNode.parentNode;setCls(this.current,'current',1);setVisibile(this.current.view,false);setCls(el,'current');setVisibile(el.view,true);this.current=el;}}}
function renderSwitcher(config){var b=$$(config.body);if(!b)return;this.body=b;this.size=config.size||4;this.itemtag=config.itemtag||'li';this.items=this.body.getElementsByTagName(this.itemtag);if(!this.items||this.items.length<=this.size)return;this.total=this.items.length;this.pc=Math.ceil(this.total/this.size)- 1;for(var i=this.size;i<this.total;i++)this.items[i].style.display='none';this.ct=$$(config.el)
if(!this.ct){this.ct=document.createElement('div');this.body.appendChild(this.ct);this.ct.style.cssText+=';clear:both';}
setCls(this.ct,'switcher-ct');var pt=config.pre||'上一组',nt=config.nextText||'下一组';var h='<a title="'+pt+'" class="switcher-previous" href="javascript:;" target="_top"></a><span class="switcher-num">';for(var i=0;i<=this.pc;i++)h+='<a href="javascript:;" for="'+ i+'" target="_top"></a>';h+='</span><a title="'+nt+'" class="switcher-next" href="javascript:;" target="_top"></a>';this.ct.innerHTML=h;setCls(this.ct.childNodes[1].firstChild,'current');this.on=0;var tthis=this;this.ct.onclick=function(e){e=window.event?window.event.srcElement:e.target;if(e.tagName.toLowerCase()=='a'){var a,b,c,d=2*tthis.size;if(e.className.indexOf('previous')>=0){if(tthis.on==0)return;a=tthis.on,tthis.on--,b=tthis.on,c=(a- 1)*tthis.size;for(var i=0;i<d;i++)if(tthis.items[i+ c])tthis.items[i+ c].style.display=i<tthis.size?'':'none';}else if(e.className.indexOf('next')>=0){if(tthis.on==tthis.pc)return;a=tthis.on,tthis.on++,b=tthis.on,c=a*tthis.size;for(var i=0;i<d;i++)if(tthis.items[i+ c])tthis.items[i+ c].style.display=i<tthis.size?'none':'';}else if(e.attributes['for']&&e.attributes['for'].value){var v=parseInt(e.attributes['for'].value);if(v==tthis.on||v<0||v>tthis.pc)return;c=tthis.on*tthis.size;for(var i=0;i<tthis.size;i++)if(tthis.items[i+ c])tthis.items[i+ c].style.display='none';a=tthis.on,tthis.on=v,b=tthis.on,c=b*tthis.size;for(var i=0;i<tthis.size;i++)if(tthis.items[i+ c])tthis.items[i+ c].style.display='';}
if(typeof a!=undefined){setCls(tthis.ct.childNodes[1].childNodes[a],'current',1);setCls(tthis.ct.childNodes[1].childNodes[b],'current');}}}}
var renderPicPlayer=function(config){this.body=$$(config.el);if(!this.body)return;this.items=this.body.getElementsByTagName('li');this.total=this.items.length;this.init(config);if(this.total==0)return;this.ct=document.createElement('div');this.ct.className='bar';this.body.appendChild(this.ct);this.switcher=document.createElement('div');this.ct.appendChild(this.switcher);this.switcher.className='slider-switch';this.title=document.createElement('h3');this.ct.appendChild(this.title);this.summary=document.createElement('p');this.ct.appendChild(this.summary);var mask=document.createElement('span');mask.className='mask';this.ct.appendChild(mask);var html='<a href="javascript:;" class="prev" title="上一张"></a>';var a,t,d,h;for(var i=0;i<this.total;i++){h=config.img?'<img src="'+this.items[i].getElementsByTagName('img')[0].src+'" /><span></span>':''
html+='<a href="javascript:;" target="_self" value="'+i+'" title="第'+(i+1)+'张">'+h+'</a>';a=this.items[i].getElementsByTagName('a')[0].href;t=this.items[i].getElementsByTagName('h3')[0].innerHTML;d=this.items[i].getElementsByTagName('p');d=d[0]?d[0].innerHTML:'';if(d)d+='<a href="'+ a+'" class="cred">[详细]</a>';this.items[i].values={href:a,title:t,desc:d};}
this.switcher.innerHTML=html+'<a href="javascript:;" class="next" title="下一张"></a>';var tthis=this;this.switcher.onclick=function(e){e=window.event?window.event.srcElement:e.target;var n=e.tagName.toLowerCase();if(n!='a'){e=e.parentNode;n=e.tagName.toLowerCase();}
if(n!='a')return;if(e.className=='prev')tthis.prev();else if(e.className=='next')tthis.next();else tthis.run(parseInt(e.attributes['value'].value));}
this.run(0);}
renderPicPlayer.prototype={_timer:null,_oth:28,index:0,srollpx:30,_srollpx:30,init:function(config){this.config={auto:true,time:1,pause:3000};Extend(this.config,config||{});if(!this.change)this.change=this.items[0].offsetWidth;this._slider=$$(this.config.slider);},setTitle:function(){var v=this.items[this.index].values;this.title.innerHTML='<a href="'+v.href+'" target="_blank">'+v.title+'</a>';this.summary.innerHTML=v.desc;setCls(this.switcher.childNodes[this.last+1],'current',1);setCls(this.switcher.childNodes[this.index+1],'current');},run:function(index){this.last=this.index||0;index==undefined&&(index=this.index);index<0&&(index=this.total- 1)||index>=this.total&&(index=0);this._target=-Math.abs(this.change)*(this.index=index);this.setTitle();this.move();},move:function(){var A=this._target,B=this._slider,C=parseInt(CurrentStyle(B)['marginLeft'])||0;if(this._timer)clearTimeout(this._timer);if(A==C){this.config.auto&&(this._timer=setTimeout(Bind(this,this.next),this.config.pause||3000));return}
var D=C<A?1:-1,E=D*(A-C),F=Math.ceil(E/3);C+=D*F;this.moveto(C);var tthis=this;this._timer=setTimeout(function(){tthis.move(A)},10);},moveto:function(i){this._slider.style['marginLeft']=i+'px'},prev:function(){this.run(this.index-1)},next:function(){this.run(this.index+1)},stop:function(){clearTimeout(this._timer);this.moveto(this._target)}};var Gallery=function(config){this.body=$$(config.body);if(!this.body)return;this.img=this.body.getElementsByTagName('img')[0];this.img.parentNode.insertBefore(document.createElement('i'),this.img);this.img.alt='';this.at=$$(config.at);this.desc=$$(config.descEl);this.sets=$$(config.setEl);this.loading=$$(config.loadEl);this.items=this.sets.getElementsByTagName('li');this.total=this.items.length;var tthis=this;this._slider=this.items[0].parentNode;this.img.onload=function(){setCls(tthis.loading,'loading',true)};if(this.total){var s=document.createElement('span');s.innerHTML='<a class="gallery-prev" target="_self" hidefocus="true" href="javascript:;"></a><a class="gallery-next" target="_self" hidefocus="true" href="javascript:;"></a>'
s.className='gallery-control';this.body.insertBefore(s,this.body.firstChild);s.firstChild.onclick=function(){tthis.prev()}
s.lastChild.onclick=function(){tthis.next()}}
this._w=this._slider.parentNode.offsetWidth;this._w2=this._w/2;for(var i=0;i<this.total;i++)this.items[i].index=i;this._slider.onclick=function(e){e=window.event?window.event.srcElement:e.target;var n=e.tagName.toLowerCase(),index;if(n=='img')index=e.parentNode.parentNode.index;else if(n=='a')index=e.parentNode.index;else if(n=='li')index=e.index;if(index!=undefined)tthis.run(index);}
this.countFullWidh();var index=location.href.indexOf('#I=');if(index){index=location.href.substring(index+ 3,location.href.length)
if(!isNaN(index))this.run(index- 1);}
if(this.total&&this._fw>this._w){var a=this.sets.getElementsByTagName('a');a[0].onmousedown=function(){tthis.srollto='right';tthis.sroll()}
a[1].onmousedown=function(){tthis.srollto='left';tthis.sroll()}
a[0].onmouseup=a[1].onmouseup=function(){tthis.srollto=false}}
setCls(tthis.loading,'loading',true);};Gallery.prototype={_timer:null,index:0,change:0,time:1,srollpx:30,_srollpx:30,run:function(index){setCls(this.loading,'loading');index==undefined&&(index=this.index);index<0&&(index=this.total- 1)||index>=this.total&&(index=0);this.index=index;setCls(this.items[this.c_index||0],'current',1);if(!this.items[this.index].src){var img=this.items[this.index].getElementsByTagName('img')[0];this.items[this.index].src=img.attributes['dataSrc']&&img.attributes['dataSrc'].value?img.attributes['dataSrc'].value:img.src;this.items[this.index].desc=img.alt||'';var w=0,i=this.index- 1;while(i>=0){w+=this.items[i].offsetWidth+ 6;i--;}
w+=this.items[this.index].offsetWidth/2+ 3;if(w>this._w2)w-=this._w2;else w=0;if((this._fw- w)<this._w)w=this._fw- this._w;if(w<0)w=0;this.items[this.index]._target=-parseInt(w);}
this.img.src=this.items[this.index].src;this.desc.innerHTML=this.items[this.index].desc;this.c_index=this.index;if(this.at)this.at.innerHTML=this.index+ 1;this._target=this.items[this.index]._target;setCls(this.items[this.index],'current');this.move();},countFullWidh:function(){this._fw=0;var w;for(var i=0;i<this.total;i++){w=this.items[i].offsetWidth;if(w<3){w=100;this.items[i].getElementsByTagName('a')[0].style.width=w+'px';}
this._fw+=w+ 6;}},move:function(){var A=this._target,B=this._slider,C=parseInt(CurrentStyle(B)['left'])||0;if(this._timer)clearTimeout(this._timer);if(A==C){this.auto&&(this._timer=setTimeout(Bind(this,this.next),this.pause||3000));return}
var D=C<A?1:-1,E=D*(A-C),F=Math.ceil(E/3);C+=D*F;this.moveto(C);var tthis=this;this._timer=setTimeout(function(){tthis.move()},10);},moveto:function(i){this._slider.style['left']=i+'px'},prev:function(){this.run(--this.index)},next:function(){this.run(++this.index)},sroll:function(){if(!this.srollto){this._srollpx=this.srollpx;return}
var l=parseInt(CurrentStyle(this._slider)['left']);if(isNaN(l))l=0;if((l==0&&this.srollto=='left')||(this.srollto=='right'&&this._fw&&l==(this._w- this._fw)))return;l+=this.srollto=='right'?-this._srollpx:this._srollpx;if(l>0)l=0;else if((l+ this._fw)<this._w)l=this._w- this._fw;this.moveto(l);this._srollpx=10;this._timer=setTimeout(Bind(this,this.sroll),15);},stop:function(){clearTimeout(this._timer);this.moveto(this._target)}};var SliderPlayer=function(config){this.body=$$(config.body);if(!this.body)return;this.loading=$$(config.loadEl);this.init();};SliderPlayer.prototype={index:0,init:function(){this.items=this.body.getElementsByTagName('li');this.total=this.items.length;this.img=document.createElement('img');var tthis=this;this.img.onload=function(){setCls(tthis.loading,'loading',true)};this.items[0].parentNode.parentNode.appendChild(this.img);if(this.total>1){var s=document.createElement('span');s.innerHTML='<a class="gallery-prev" target="_self" hidefocus="true" href="javascript:;"></a><a class="gallery-next" target="_self" hidefocus="true" href="javascript:;"></a>'
s.className='gallery-control';var tthis=this;var p=this.items[0].parentNode;p.parentNode.insertBefore(s,p);s.firstChild.onclick=Bind(this,this.prev);s.lastChild.onclick=Bind(this,this.next);}
this.renderSwitcher();setCls(tthis.loading,'loading',true);},renderSwitcher:function(){var sets=document.createElement('div'),p=this.body.parentNode,img,li,html='';sets.className='pt-switcher';sets.innerHTML='<a href="javascript:;" class="prev"></a><div class="pt-list"><ul></ul></div><a href="javascript:;" class="next"></a>';this.body.nextSibling?p.insertBefore(sets,this.body.nextSibling):p.appendChild(sets);this.listct=sets.childNodes[1].childNodes[0];this._w=sets.childNodes[1].offsetWidth;this._fw=0;var _w=parseInt(this._w/2);for(var i=0;i<this.total;i++){img=this.items[i].getElementsByTagName('img')[0];this.items[i].src=this.items[i].getElementsByTagName('a')[0].href;li=document.createElement('li');li.index=i;li.innerHTML='<span><a href="javascript:;"><img src="'+img.src+'" /></a><em><font>'+(i+1)+'</font></em></span>';this.listct.appendChild(li);li.target=_w- this._fw- parseInt(li.offsetWidth/2);if(li.target>0)li.target=0;this._fw+=li.offsetWidth;}
this.run(0);var tthis=this;this.listct.onclick=Bind(this,this.onSwicherEvent);if(this.total&&this._fw>this._w){var a=sets.getElementsByTagName('a');sets.firstChild.onmousedown=function(){tthis.srollto='left';tthis.sroll()}
sets.lastChild.onmousedown=function(){tthis.srollto='right';tthis.sroll()}
sets.firstChild.onmouseup=sets.lastChild.onmouseup=function(){tthis.srollto=false}}},onSwicherEvent:function(e){e=window.event?window.event.srcElement:e.target;if(e.tagName.toLowerCase()=='img'){var index=parseInt(e.parentNode.parentNode.parentNode.index);this.run(index);}},run:function(index){setCls(this.loading,'loading');if(this.timer)clearTimeout(this.timer);index=index||0;index<0&&(index=this.total- 1)||index>=this.total&&(index=0);setCls(this.listct.childNodes[this.index],'current',1);this.listct.childNodes[this.index].childNodes[0].lastChild.firstChild.innerHTML=this.index+ 1;this.img.src=this.items[index].src;setCls(this.listct.childNodes[index],'current');this.listct.childNodes[index].childNodes[0].lastChild.firstChild.innerHTML=index+ 1+'/'+ this.total;this.index=index;this.move();if(this.auto)this.timer=setTimeout(Bind(this,this.next),this.pause||3000);},prev:function(){this.run(this.index-1)},next:function(){this.run(this.index+1)},move:function(){if(this.listct.timer)clearTimeout(this.listct.timer);var B=this.listct,A=B.childNodes[this.index].target,C=parseInt(CurrentStyle(B)['marginLeft'])||0;if(A==C)return;var D=C<A?1:-1,E=D*(A-C),F=Math.ceil(E/3);C+=D*F;if((C+this._fw)<this._w)C=this._w- this._fw;if(C>0)C=0;this.listct.style.marginLeft=C+'px';this.listct.timer=setTimeout(Bind(this,this.move),10);},srollpx:30,_srollpx:30,sroll:function(){if(this.listct.timer)clearTimeout(this.listct.timer);if(!this.srollto){this._srollpx=this.srollpx;return}
var l=parseInt(CurrentStyle(this.listct)['marginLeft']);if(isNaN(l))l=0;if((l==0&&this.srollto=='left')||(this.srollto=='right'&&this._fw&&l==(this._w- this._fw)))return;l+=this.srollto=='right'?-this._srollpx:this._srollpx;if(l>0)l=0;else if((l+ this._fw)<this._w)l=this._w- this._fw;this.listct.style.marginLeft=l+'px';this._srollpx=10;this.listct.timer=setTimeout(Bind(this,this.sroll),15);}};function setListMode(A,B,C,D){var E=A.parentNode.getElementsByTagName('a');for(var I=0,L=E.length;I<L;I++)setCls(E[I],'current',1);setCls(A,'current');if(B=$$(B))setCls(B,C,!D);}
function setFontSize(O,E,F){var A=O.parentNode.getElementsByTagName('font');for(var i=0,len=A.length;i<len;i++)setCls(A[i],'current',1);setCls(O,'current');if(E=$$(E))E.style.fontSize=F+'px';}
function copyLink(title){copyToClipboard(window.location.href)}
function copyToClipboard(txt){if(window.clipboardData){window.clipboardData.clearData();window.clipboardData.setData("Text",txt);}else if(navigator.userAgent.indexOf("Opera")!=-1){window.location=txt;}else if(window.netscape){try{netscape.security.PrivilegeManager.enablePrivilege("UniversalXPConnect");}catch(e){alert("您的firefox安全限制限制您进行剪贴板操作.\n请打开'about:config'将signed.applets.codebase_principal_support'设置为true'之后重试");return false;}
var clip=Components.classes["@mozilla.org/widget/clipboard;1"].createInstance(Components.interfaces.nsIClipboard);if(!clip)return;var trans=Components.classes["@mozilla.org/widget/transferable;1"].createInstance(Components.interfaces.nsITransferable);if(!trans)return;trans.addDataFlavor('text/unicode');var str=new Object();var len=new Object();var str=Components.classes["@mozilla.org/supports-string;1"].createInstance(Components.interfaces.nsISupportsString);var copytext=txt;str.data=copytext;trans.setTransferData("text/unicode",str,copytext.length*2);var clipid=Components.interfaces.nsIClipboard;if(!clip)
return false;clip.setData(trans,null,clipid.kGlobalClipboard);}
alert('链接已经复制, 请粘贴到您的QQ/MSN上发送给您的好友.');}
function digg(id,o,action){var diggpage=false;if(typeof o=='string'){o=$$(o);diggpage=true;}
if(o.title=='已顶过'){alert('您已顶过本内容，不能重复顶');return}
if(Cookies.processCookeiIds('digg',id,20)){alert('您刚才已表决过了，不能重复表决');return}
ajax.request('get',action?action:content_action,{success:function(response){var v=ajax.jsondecode(response.responseText);if(diggpage){o.innerHTML=v['digg'];return;}else{setDiggValue(v);}}},{contentid:id,act:'digg'});o.title='已顶过';}
function trample(id,o,action){if(o.title=='已踩过'){alert('您已踩过本内容，不能重复踩');return}
if(Cookies.processCookeiIds('digg',id,20)){alert('您刚才已表决过了，不能重复表决');return}
ajax.request('get',action?action:content_action,{success:function(response){var v=ajax.jsondecode(response.responseText);setDiggValue(v);}},{contentid:id,act:'trample'});o.title='已踩过';}
function processCookeiIds(){}
var PAGE_CONTENT={};function getContentInfo(id,action,model){ajax.request('get',action?action:content_action,{success:function(response){var v=ajax.jsondecode(response.responseText);PAGE_CONTENT.click=v['click']||0;PAGE_CONTENT.comment=v['comment']||0;PAGE_CONTENT.download=v['download']||0;setInnerHtml('content_click',PAGE_CONTENT.click);setDiggValue(v);setInnerHtml('comment_count_0',PAGE_CONTENT.comment);setInnerHtml('comment_count_1',PAGE_CONTENT.comment);setInnerHtml('comment_count_2',PAGE_CONTENT.comment);setInnerHtml('comment_count_3',PAGE_CONTENT.comment);setInnerHtml('content_download',PAGE_CONTENT.download);}},{contentid:id,model:model});}
function setDiggValue(v){setInnerHtml('content_op_support',v.digg||0);setInnerHtml('content_op_oppose',v.trample||0);setInnerHtml('content_diggpercent','('+(v.diggpercent||0)+'%)');setInnerHtml('content_tramplepercent','('+(v.tramplepercent||0)+'%)');}
function getContentSupport(ids,action){ajax.request('get',action?action:content_action,{success:function(response){var v=ajax.jsondecode(response.responseText);setInnerHtml('content_click',v['click']?v['click']:0);}},{contentids:ids});}
function setInnerHtml(element,value,script){if(typeof element!=='object'){element=$$(element);}
if(element){script?set_innerHTML(element,value):element.innerHTML=value;}}
function resizeImage(img,fitWidth,fitHeight,self){fitWidth=fitWidth||600;var tempImg=new Image();tempImg.src=img.src;var scale=1.0;var width=0,height=0;if(document.all){if(tempImg.readyState=='complete'){width=tempImg.width;height=tempImg.height;}}
else(tempImg.complete)
{width=tempImg.width;height=tempImg.height;}
if(fitWidth<width){scale=width/height;if(width>fitWidth){width=fitWidth;height=width/scale;if(height>fitHeight)
{height=fitHeight;width=height*scale;}}
if(height>fitHeight){height=fitHeight;width=height*scale;}
if(width==0||height==0){width=fitWidth;height=fitHeight;}
img.width=width;img.height=height;img.style.width=width+'px';img.style.height=height+'px';}
if(self){var x=parseInt((fitWidth- width)/ 2);var y=parseInt((fitHeight- height)/ 2);img.style.marginTop=y+'px';img.style.marginLeft=x+'px';}else{img.parentNode.style.width=width+'px';}}
function setImageView(img,width,desc){resizeImage(img,width)}
function setCurrentDateTime(o){var d=new Date();var da=d.getDate();var mo=d.getMonth()+ 1;var y=d.getFullYear();var h=d.getHours();if(h<10){h='0'+h}
var m=d.getMinutes();if(m<10){m='0'+m}
var s=d.getSeconds();if(s<10){s='0'+s}
var week=['天','一','二','三','四','五','六'];if(typeof(o)!='object'){o=$$(o)}
o.innerHTML=y+'年'+mo+'月'+da+'日 星期'+week[d.getDay()]+'<br />'+h+':'+m+':'+s;window.setTimeout(function(){setCurrentDateTime(o)},1000);}
function ApplyLink(){var ct=$$('applylink');if(ct.style.display=='block')return;ct.style.display='block';var h=ct.offsetHeight;ct.style.height='1px';var tm=window.setInterval(function(){var c_h=ct.offsetHeight;if(c_h>=h){ct.style.height=h+'px';window.clearInterval(tm);return;}var t=(h-c_h)/10;if(Math.abs(t)>.1){c_h+=t}ct.style.height=c_h+'px';},10);}
function checkLinkForm(f){if(f.sitename.value.trim().trim()==''){alert('请填写您的网站名称');f.sitename.focus();return false;}
var logo=f.logo.value.trim();if(logo!=''&&!isUrl(logo)){alert("您的网站Logo地址不正确，请重新填写\n请输入您网站的Logo网址");f.logo.focus();return false;}
var url=f.url.value.trim();if(url==''){alert('请填写您的链接Url');f.url.focus();return false;}
if(!isUrl(url)){alert('您的链接Url格式不正确，请重新填写');f.url.focus();return false;}
if(f.name.value.trim()==''){alert('请填写您的链接Url');f.name.focus();return false;}
var email=f.email.value.trim();if(email==''){alert('请填写您的Email');f.email.focus();return false;}
if(!isEmail(email)){alert('您的Email格式不正确，请重新填写');f.email.focus();return false;}
if(f.category&&f.category.value.trim()==''){alert('请选择友情链接分类');f.category.focus();return false;}
try{var ct=$$('linkmaskct')
ct.style.display='block';var c=$$('applylink');var w=c.offsetWidth;var h=c.offsetHeight;var t=$$('linkmasktxt')
var t_w=t.offsetWidth;var t_h=t.offsetHeight;t.style.left=((w- t_w)/ 2) + 'px';t.style.top=((h- t_h)/ 2) + 'px';ajax.request('post',f.action,{success:function(r){window.setTimeout(function(){ct.style.display='none';var v=ajax.jsondecode(r.responseText);if(v.success==1){f.reset();c.style.display='none';alert(v.message)}else{alert(v.message?v.message:r.responseText)}},100)},failure:function(r){ct.style.display='none';alert(r.status+"错误，请与管理员联系")}},ajax.serializeForm(f));return false;}catch(e){return true;}}
function doLinkClick(id,action){ajax.request('post',action,{},{id:id})}
var Cookies={set:function(name,value){var argv=arguments;var argc=arguments.length;var expires=null;if(argc>2){var expires=new Date();expires.setDate(expires.getDate()+ argv[2]);}
var path=(argc>3)?argv[3]:'/';var domain=(argc>4)?argv[4]:null;var secure=(argc>5)?argv[5]:false;document.cookie=name+"="+ escape(value)+
((expires==null)?"":("; expires="+ expires.toGMTString()))+
((path==null)?"":("; path="+ path))+
((domain==null)?"":("; domain="+ domain))+
((secure==true)?"; secure":"");},get:function(name){var arg=name+"=";var alen=arg.length;var clen=document.cookie.length;var i=0;var j=0;while(i<clen){j=i+ alen;if(document.cookie.substring(i,j)==arg)
return Cookies.getCookieVal(j);i=document.cookie.indexOf(" ",i)+ 1;if(i==0)
break;}
return null;},clear:function(name){if(this.get(name)){var expdate=new Date();expdate.setTime(expdate.getTime()-(86400*1000*1));this.set(name,"",expdate);}},getCookieVal:function(offset){var endstr=document.cookie.indexOf(";",offset);if(endstr==-1){endstr=document.cookie.length;}
return unescape(document.cookie.substring(offset,endstr));},processCookeiIds:function(type,contentid,idscount,unset){var savedids=this.get(type);if(savedids!=null){var savedids_array=savedids.split(',');var saved=false;savedids='';var j=1;for(var i=savedids_array.length-1;i>=0;i--){if(savedids_array[i]==contentid&&saved)continue;else{if(savedids_array[i]==contentid&&!saved)saved=true;savedids+=(savedids==''?savedids_array[i]:','+savedids_array[i]);j++;if(j==idscount&&saved)break;if(j==idscount-1&&!saved)break;}}
if(saved){return true;}else if(!unset){savedids+=','+ contentid;this.set(type,savedids,1);return false;}}else if(!unset){this.set(type,contentid,1);return false;}}};Login={form:new Array,login:false,isLogin:function(url,form,type){if(!url)return;var tthis=this;url+=url.indexOf('?')<0?'?':'&';url+='logintype='+ type;ajax.request('get',url,{success:function(r){var v=ajax.jsondecode(r.responseText);if(v&&v.success==1)tthis.logined(form,v.message);}});},logined:function(form,msg){this.login=true;if(typeof form!='object'){form=$$(form);}
var account=document.createElement('div');account.className='accountinfo';account.innerHTML=msg;form.parentNode.form=form;form.parentNode.insertBefore(account,form);form.account=account;setVisibile(form,false);},logout:function(o,url){if(!url)return;var tthis=this;ajax.request('get',url,{success:function(r){var v=ajax.jsondecode(r.responseText);if(v&&v.success==1){tthis.login=false;var account=o.parentNode;var form=account.parentNode.form||null;if(form.username){var u=form.username.value;form.reset();form.username.value=u;}
setVisibile(form,true);account.parentNode.removeChild(account);if(v.logoutinfo)tthis.sysnLogin(v.logoutinfo);}}});},submit:function(A){var flag=true;if(A.username.value.trim()==''){A.username.focus();setVisibile('username_valid',true);flag=false;}
if(A.password.value.trim()==''){A.password.focus();setVisibile('password_valid',true);flag=false;}
if(flag){var tthis=this;ajax.request('post',A.attributes['action'].value,{success:function(r){var v=ajax.jsondecode(r.responseText);if(v&&v.success==1){if(v.logininfo)tthis.sysnLogin(v.logininfo);tthis.logined(A,v.message);if(A.loginforward&&A.loginforward.value!='')window.location.href=A.loginforward.value;}else if(v.success==0){alert(v.message);}else{alert('请求服务器异常，请稍候再登录')}}},ajax.serializeForm(A));}
return false;},sysnLogin:function(msg){var d=document.createElement('div');document.body.appendChild(d);ajax.setInnerHTML(d,msg);},forwardInit:function(A,B,C,D){if(A.render)return;A.render=true;if(typeof B=='string')B=$$(B);if(!B)return;A.L=B;B.O=A;A.L.eventEls=[A,A.L];A.L.check=function(e){if(!this.eventObj)return;var t=window.event?window.event.srcElement:e.target;var d=5;while(d>0){if(this.eventObj.eventEls.indexOf(t)>=0){return}
else if(t.parentNode){t=t.parentNode}
else break;d--;}
this.eventObj.hide();}
A.L.show=function(){document.eventObj=this;onEvent(document,'click',this.check);this.style.display='block';this.isshow=true}
A.L.hide=function(){document.eventObj=null;onEvent(document,'click',this.check);setCls(this.O,'combo_o',1);this.style.display='none';this.isshow=false;}
A.onclick=function(){setCls(this,'combo_o');this.L.show()}
A.onmouseout=function(){if(!this.L.isshow)setCls(this,'combo_o',1)}
var LI=A.L.getElementsByTagName('li');for(var I=0;I<LI.length;I++){if(LI[I].className!='bd'){LI[I].onclick=function(){$$(C).value=this.attributes['value'].value;A.innerHTML=this.innerHTML;this.parentNode.hide();}}
LI[I].onmouseover=function(){if(this.className!='bd')setCls(this,'hover');}
LI[I].onmouseout=function(){if(this.className!='bd')setCls(this,'hover',true);}}}};function shareContent(app_url,url_param,title_param){app_url+=app_url.indexOf('?')<0?'?':'&';app_url+=url_param+'='+ encodeURIComponent(window.location.href);if(title_param){var title=$$('content_title');title=title?title.innerHTML:document.title;app_url+='&'+ title_param+'='+ encodeURIComponent(title);}
window.open(app_url);}
var favoriteeditor;function addToFavorite(contentid,url){if(!favoriteeditor){ajax.request('get',url,{success:function(r){var v=ajax.jsondecode(r.responseText);if(v&&v.success&&v.success==-1){Account.login({callback:function(){addToFavorite(contentid,url)}});}else{favoriteeditor=Account.window({id:'addfavorite',title:'添加新收藏',width:525});favoriteeditor.body.style.height='auto';ajax.setInnerHTML(favoriteeditor.body,r.responseText);var f=favoriteeditor.body.getElementsByTagName('form')[0];FormPanel.renderInput(f);var title=$$('content_title');f.title.value=title?title.innerHTML:document.title;var description=$$('content_description');if(description){f.description.value=description.innerHTML;}else{var metas=document.getElementsByTagName('meta');for(var i=0,len=metas.length;i<len;i++){var meta_name=metas[i].getAttribute('name');if(meta_name&&meta_name.toLowerCase()=='description'){f.description.value=metas[i].getAttribute('content')?metas[i].getAttribute('content'):'';break;}}}
f.url.value=window.location.href;favoriteeditor.show();}}},{action:'editor'});}else{Account.hiddenAllError($$('ajaxFavoriteEditor'));favoriteeditor.show();}}
var isIE6=navigator.userAgent&&navigator.userAgent.split(";")[1].toLowerCase().indexOf("msie 6.0")=="-1"?false:true;var soImgMaxWidth=140,soImgMaxHeight=140;function soImgShow(A,B){if(B){A.parentNode.style.width='auto';A.parentNode.style.height='auto';}else{A.style.display='none';A.parentNode.style.width='100px';A.parentNode.style.height='100px';return;}
if(!isIE6)return;var W=soImgMaxWidth,H=soImgMaxHeight,T=new Image();T.src=A.src;var w=0,h=0;if(T.readyState=='complete'){w=T.width,h=T.height}
if(!w||!h||(w<W&&h<H))return;if((w/W)>(h/H)){h=h*W/w;w=W;}else{w=w*H/h;h=H;}
A.width=w;A.height=h;A.style.width=w+'px';A.style.height=h+'px';}
function set_innerHTML(el,html){var ua=navigator.userAgent.toLowerCase();if(ua.indexOf('msie')>=0&&ua.indexOf('opera')<0){html='<div style="display:none">for IE</div>'+ html;html=html.replace(/<script([^>]*)>/gi,'<script$1 defer>');el.innerHTML=html;el.removeChild(el.firstChild);}else{var C=html.replace(/<script[^>]*>([\s\S]*?)<\/script>/mgi,"");el.innerHTML=C;if(html.length==C.length)return;var id=new Date();id='excms_id_'+ id.getTime();html+='<span id="'+id+'"></span>';var hd=document.getElementsByTagName("head")[0];var re=/(?:<script([^>]*)?>)((\n|\r|.)*?)(?:<\/script>)/ig;var srcRe=/\ssrc=([\'\"])(.*?)\1/i;var typeRe=/\stype=([\'\"])(.*?)\1/i;var match;while(match=re.exec(html)){var attrs=match[1];var srcMatch=attrs?attrs.match(srcRe):false;if(srcMatch&&srcMatch[2]){var s=document.createElement("script");s.src=srcMatch[2];var typeMatch=attrs.match(typeRe);if(typeMatch&&typeMatch[2]){s.type=typeMatch[2];}
hd.appendChild(s);}else if(match[2]&&match[2].length>0){if(window.execScript){window.execScript(match[2]);}else{window.eval(match[2]);}}}
var el=document.getElementById(id);if(el){el.parentNode.removeChild(el)}}}
function initBgMenu(W){var A=$$('menuitems').getElementsByTagName('a'),B,C,F;for(var i=0,l=A.length;i<l;i++){B=A[i];if(B.className=='current')C=B;B.M=$$(B.id.replace('mn','nav_menu'));B.M.T=B;B.M.onmouseout=B.onmouseout=function(e){var E=this.M?this:this.T;if(E.timer)window.clearTimeout(E.timer);if(!W)E.timer=window.setTimeout(function(){setCls(E,'current',1);setVisibile(E.M);if(C){setCls(C,'current');setVisibile(C.M,true)}else{F=null}},50);}
B.onmouseover=B.M.onmouseover=function(){var E=this.M?this:this.T;if(E.timer)window.clearTimeout(E.timer);if(C){setCls(C,'current',1);setVisibile(C.M)}
if(F){if(F.timer)window.clearTimeout(F.timer);setCls(F,'current',1);setVisibile(F.M)}
setCls(E,'current');setVisibile(E.M,true);F=E;}}}
function _Click(){var A=$$('_CI');try{var el=$$('content_click');el.parentNode.style.display='none';return;A=A.className.split(' ');A=A[1].replace('ci','');if(isNaN(A))return;getContentInfo(A,'http://www.chyxx.com/app/content');}catch(e){}
initBgTab();}
var isInitBgTab=false;function initBgTab(){if(isInitBgTab)return;isInitBgTab=true;var el=$$('contentBody');var t=el.parentNode.getElementsByTagName('div')[1];if(t.className!='reportTab')return;var html=el.innerHTML;var as=t.getElementsByTagName('a');el.innerHTML=html.replace('报告目录：','<span class="fr"><a href="#bgname">价格</a>-<a href="#abstract">摘要</a>-<a href="#chart">图表</a>-<a href="'+as[3].href+'" target="_blank">订购</a>-<a href="'+as[4].href+'" target="_blank">下载</a></span><a name="catalogue" id="bgcatalogue"></a>报告目录').replace('图表目录','<span class="fr"><a href="#bgname">价格</a>-<a href="#abstract">摘要</a>-<a href="#catalogue">目录</a>-<a href="'+as[3].href+'" target="_blank">订购</a>-<a href="'+as[4].href+'" target="_blank">下载</a></span><a name="chart" id="bgchart"></a>图表目录');setCls($$('bgcatalogue').parentNode,'bgcatalogue');setCls($$('bgchart').parentNode,'bgchart');var a=document.createElement('a');a.name='abstract';el.parentNode.insertBefore(a,t);}
function _CO(F){if(F.lxr.value.trim()==''){alert('请填写您的姓名');F.lxr.focus();return false;}
if(F.tel.value.trim()==''){alert('请填写您的联系电话或手机号码');F.tel.focus();return false;}
return true;}